apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-wrapper-script
data:
  # A simple Node.js wrapper that exposes the STDIO server via HTTP (SSE)
  server.js: |
    const { spawn } = require('child_process');
    const http = require('http');
    
    // Start the 'everything' server process
    const mcpProcess = spawn('npx', ['-y', '@modelcontextprotocol/server-everything'], {
      stdio: ['pipe', 'pipe', process.stderr]
    });

    const server = http.createServer((req, res) => {
      // Simple SSE implementation (This is a simplified mock for connectivity testing)
      // In a real scenario, use the official @modelcontextprotocol/sdk to host SSE
      if (req.url === '/sse') {
        res.writeHead(200, {
          'Content-Type': 'text/event-stream',
          'Cache-Control': 'no-cache',
          'Connection': 'keep-alive'
        });
        mcpProcess.stdout.on('data', (data) => {
          res.write(`data: ${data.toString()}\n\n`);
        });
        req.on('close', () => res.end());
      } else if (req.method === 'POST') {
        req.pipe(mcpProcess.stdin, { end: false });
        res.writeHead(200);
        res.end('ok');
      } else {
        res.writeHead(404);
        res.end();
      }
    });
    server.listen(8080, () => console.log('MCP SSE Wrapper running on 8080'));

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-demo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-demo
  template:
    metadata:
      labels:
        app: mcp-demo
    spec:
      containers:
        - name: node-wrapper
          image: node:20-alpine
          command: ["node", "/app/server.js"]
          volumeMounts:
            - name: script-volume
              mountPath: /app
      volumes:
        - name: script-volume
          configMap:
            name: mcp-wrapper-script
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-demo-service
spec:
  selector:
    app: mcp-demo
  ports:
    - port: 80
      targetPort: 8080